export const COLORS = {
    WARM_GREENISH_YELLOW: "#C4C50A",
    PRIMARY_MAGENTA: "#BB016A",
    DEEP_LAVENDER: "#8F6FB9",
    LIGHT_CHOCOLATE_BROWN: "#D8B894",
    BANKNOTE_GREEN: "#0B6E4F",
    PRIMARY_SAFFRON: "#FF9933",
};

export const COLOR_ARRAY = [
    COLORS.LIGHT_CHOCOLATE_BROWN,
    COLORS.BANKNOTE_GREEN,
    COLORS.PRIMARY_SAFFRON
];
